#define CMDCODE_SHOW_NW_TOPOLOGY 0 // show topology
#define CMDCODE_SHOW_TOPOLOGIES_SAVED 1
#define CMDCODE_SHOW_TOPOLOGY_ID 2
#define CMDCODE_SHOW_NODE 3
#define CMDCODE_SHOW_NODE_ARP_TABLE 4
#define CMDCODE_SHOW_NODE_MAC_TABLE 5
#define CMDCODE_SHOW_NODE_INTERFACES 6
#define CMDCODE_SHOW_NODE_INTERFACE_MODE 7
#define CMDCODE_SHOW_NODE_INTERFACE_VLANS 8
#define CMDCODE_SHOW_NODE_DEBUG_STATUS 9
#define CMDCODE_SHOW_NODE_ROUTE_TABLE 10

#define CMDCODE_CONFIG_NODE_DEBUG 100
#define CMDCODE_CONFIG_NODE_MODE 101
#define CMDCODE_CONFIG_NODE_INTERFACE_VLAN_ADD 102
#define CMDCODE_CONFIG_NODE_INTERFACE_VLAN_REMOVE 103
#define CMDCODE_CONFIG_NODE_ROUTE_DEST 104
#define CMDCODE_CONFIG_NODE_ROUTE_MASK 105
#define CMDCODE_CONFIG_NODE_ROUTE_GW 106
#define CMDCODE_CONFIG_NODE_ROUTE_OIF 107
#define CMDCODE_CONFIG_TOPOLOGY_LOAD 108
#define CMDCODE_CONFIG_TOPOLOGY_CREATE 109

#define CMDCODE_RUN_NODE_RESOLVE_ARP 300