#define CMDCODE_SHOW_NW_TOPOLOGY 1 // show topology
#define CMDCODE_SHOW_NODE 2
#define CMDCODE_SHOW_NODE_ARP_TABLE 3 
#define CMDCODE_SHOW_NODE_MAC_TABLE 4
#define CMDCODE_SHOW_NODE_INTERFACES 5
#define CMDCODE_SHOW_NODE_INTERFACE_MODE 6
#define CMDCODE_SHOW_NODE_INTERFACE_VLANS 7
#define CMDCODE_SHOW_NODE_DEBUG_STATUS 8
#define CMDCODE_SHOW_NODE_ROUTE_TABLE 9

#define CMDCODE_RUN_NODE_RESOLVE_ARP 300 //
#define CMDCODE_RUN_NODE_DEBUG_STATUS 301 
#define CMDCODE_RUN_NODE_MODE 302
#define CMDCODE_RUN_NODE_INTERFACE_VLAN_ADD 303
#define CMDCODE_RUN_NODE_INTERFACE_VLAN_REMOVE 303