#ifndef __TCPCONST_H__
#define __TCPCONST_H__

#define ARP_PACKET 0x0806
#define ARP_REQUEST 1
#define ARP_REPLY 2

#define ETH_HW 1
#define ETH_HW_LEN 6

#define IP_PROTO_LEN 4
#define IP_PROTO 0x0800

#define ICMP_PROTO 1
#define ICMP_TYPE_ECHO 8
#define ICMP_TYPE_ECHO_REPLY 0

#define ICMP_TYPE_ECHO_REPLY 0
#define ICMP_TYPE_ECHO_MESSAGE 8
#define ICMP_TYPE_DEST_UNREACH 3
#define ICMP_TYPE_TIME_EXCEEDED 11

#define ICMP_CODE_ECHO 0
#define ICMP_CODE_DEST_UNREACH_NET 0
#define ICMP_CODE_DEST_UNREACH_HOST 1
#define ICMP_CODE_TIME_EXCEEDED_TTL 0
#define ICMP_CODE_TIME_EXCEEDED_FRAGEMENT 1

#define BROADCAST_MAC 0xFFFFFFFFFFFF

#define VLAN_TAG 0x8100

#endif
